#!/bin/bash

source _common.sh


# We want the PR template to have the correct markers,
# adn we want these markers to be the same as in the script.

EXPECTED_START_MARKER="<!-- 🤖 FORWARD PORTING BEGIN -->"
EXPECTED_END_MARKER="<!-- 🤖 FORWARD PORTING END -->"

PULL_REQUEST_TEMPLATE_FILE="$__PROJECT_ROOT__/.github/pull_request_template.md"
SCRIPT_FILE="$__FORWARD_PORTING_ROOT__/forward-port-missing"

function test_find_forward_porting_markers_in_PR_template() {
    # Check that the PR template contains the expected markers
    assert "test -f $PULL_REQUEST_TEMPLATE_FILE" "PR template file does not exist."

    local content=$(cat "$PULL_REQUEST_TEMPLATE_FILE")
    assert "echo \"$content\" | grep -q \"$EXPECTED_START_MARKER\"" "PR template does not contain the expected start marker."
    assert "echo \"$content\" | grep -q \"$EXPECTED_END_MARKER\"" "PR template does not contain the expected end marker."
}

function test_find_forward_porting_markers_in_script() {
    # Check that the script contains the expected markers
    assert "test -f $SCRIPT_FILE" "Script file does not exist."

    local content=$(cat "$SCRIPT_FILE")
    echo $content | grep "${EXPECTED_START_MARKER}" &>/dev/null
    assert_equals $? 0 "Script does not contain the expected start marker."
    echo $content | grep "${EXPECTED_END_MARKER}" &>/dev/null
    assert_equals $? 0 "Script does not contain the expected end marker."
}