# This workflow supports jobs which needs the on.issue_comment event
# instead of the usual on.pull_request event.
name: Forward port missing
run-name: Forward port missing ${{ github.ref }}

on:
  issue_comment:
    types: [created, edited, deleted]

# jobs:
#   forward-port-missing:
#     permissions:
#       pull-requests: write
#     name: Forward port missing
#     uses: lczyk/chisel-releases-workflow-testing/.github/workflows/forward-port-missing.yaml@main



jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: Forward port missing
    if: ${{ github.event.issue.pull_request }}
    permissions:
      pull-requests: write
    uses: lczyk/chisel-releases-workflow-testing/.github/workflows/forward-port-missing.yaml@main

  # issue_commented:
  #   # This job only runs for issue comments
  #   name: Issue comment
  #   if: ${{ !github.event.issue.pull_request }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo A comment on issue $NUMBER
  #       env:
  #         NUMBER: ${{ github.event.issue.number }}
