# This workflow triggers only when any changes (including the initial PR)
# are made to the topmost comment of a pull request -- the one made by the
# author when they open the PR.
name: PR message
run-name: PR message ${{ github.ref_name }}

on:
  pull_request:
    types: [opened, edited]
    branches:
      - "ubuntu-*"

jobs:
  forward-port-missing:
    # Trigger only when the PR body is changed
    if: |
      (github.event.action == 'opened' && github.event.pull_request.body) ||
      (github.event.action == 'edited' && github.event.changes.body)
    
    # We need write permissions to the pull request
    # to be able to update the labels
    permissions:
      pull-requests: write

    # Call the forward-port-missing workflow
    # It will be called with the same event payload as this workflow
    # so it can access the PR body (github.event.pull_request.body) 
    name: Forward port missing
    uses: lczyk/chisel-releases-workflow-testing/.github/workflows/forward-port-missing.yaml@main
