# This workflow triggers only when any changes (including the initial PR)
# are made to the topmost comment of a pull request -- the one made by the
# author when they open the PR.
name: PR message
run-name: PR message ${{ github.ref_name }}

on:
  pull_request:
    types: [created, edited]
    branches:
      - "ubuntu-*"

jobs:
  # debug:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Echo all the event data
  #       run: echo '${{ toJson(github) }}'

  forward-port-missing:
    if: |
      # There were changes to the PR body
      github.event.action == 'edited' && github.event.changes.body
    # runs-on: ubuntu-latest
    name: Forward port missing
    uses: lczyk/chisel-releases-workflow-testing/.github/workflows/forward-port-missing.yaml@main
