# This workflow triggers only when any changes (including the initial PR)
# are made to the topmost comment of a pull request -- the one made by the
# author when they open the PR.
name: PR message
run-name: PR message ${{ github.ref_name }}

on:
  pull_request:
    types: [opened, edited]
    branches:
      - "ubuntu-*"

jobs:
  forward-port-missing:
    # Trigger only when the PR body is changed
    if: |
      (github.event.action == 'opened' && github.event.pull_request.body) ||
      (github.event.action == 'edited' && github.event.changes.body)
    # runs-on: ubuntu-latest
    name: Forward port missing
    uses: lczyk/chisel-releases-workflow-testing/.github/workflows/forward-port-missing.yaml@main
