name: Debug workflow
run-name: Debug workflow for ${{ github.ref_name }}

on: 
  branch_protection_rule:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  merge_group:
  milestone:
  page_build:
  public:
  pull_request:
    branches:
      - "ubuntu-*"
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - locked
      - unlocked
      - ready_for_review
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  push:
  registry_package:
  release:
  repository_dispatch:
  status:
  watch:
  workflow_call:
  workflow_dispatch:
    

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Echo all the event data
        run: echo '${{ toJson(github) }}'
