name: "Deploy on Comment"

on:
  issue_comment:
    types: [created, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '<!-- 🤖 PR -->')
    steps:
      - name: Debug
        run: |
          echo ${{ github.event.comment.body }}
      # - name: Checkout
      #   uses: actions/checkout@v3

      # - name: Deploy
      #   run: |
      #     echo "Deploying..."
