name: "Deploy on Comment"

on:
  issue_comment:
    types: [created, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Check that we are a PR event and that the comment has the special marker
    # We want to check that in the `if` condition so we don't even launch the 
    # job and not waste resources.
    if: |
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '<!-- 🤖 PR -->')
    steps:
      - name: Debug
        run: |
          echo ${{ github.event.comment.body }}
      # - name: Checkout
      #   uses: actions/checkout@v3

      # - name: Deploy
      #   run: |
      #     echo "Deploying..."
