name: "Deploy on Comment"

on:
  issue_comment:
    types: [created, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Check that we are a PR event and that the comment has the special marker
    # We want to check that in the `if` condition so we don't even launch the 
    # job and not waste resources.
    if: |
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '<!-- 🤖 PR -->')
    steps:
      # This is a javascript step since it handles emoji better
      - name: Remove emoji from body
        uses: actions/github-script@v6
        id: body-cleanup
        with:
          script: |
            const body = process.env.GITHUB_EVENT_COMMENT_BODY;
            // Remove the emoji from the body
            const cleanedBody = body.replace(/<img[^>]*>/g, '');
            // Set the cleaned body as an output variable
            console.log(`::set-output name=cleaned_body::${cleanedBody}`);
      
      - name: Echo cleaned body
        run: echo "${{ steps.body-cleanup.outputs.cleaned_body }}"
          
      - name: Generate an output variable
        id: set_variable  # Give this step a unique ID
        run: |
          # Generate a value (e.g., a dynamic version number)
          my_version="1.2.3"
          # Write the variable to the GITHUB_OUTPUT file
          echo "version=$my_version" >> $GITHUB_OUTPUT

      - name: Use the variable in a later step
        run: |
          echo "The generated version is ${{ steps.set_variable.outputs.version }}"
